import type { Metadata } from "next";
import "./globals.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="h-[1000000] sm:text-red-300 md:text-amber-200 lg:text-blue-400 "
      >
        {children}
      </body>
    </html>
  );
}
